Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -77,14 +77,25 @@ jobs:
       - name: Wait for Terraform HCP Run Completion
         run: |
           start_time=$(date +%s)
-          timeout=180
+          timeout=240 # 4 minutes in seconds
+
           while true; do
-            status=$(curl \
-              --header "Authorization: Bearer ${{ env.TF_API_TOKEN }}" \
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))
+
+            if [ $elapsed_time -gt $timeout ]; then
+              echo "Error: Terraform run exceeded maximum polling duration of 4 minutes."
+              exit 1
+            fi
+
+            # Fetch the run status
+            response=$(curl \
+              --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
               --header "Content-Type: application/vnd.api+json" \
               --request GET \
-              https://app.terraform.io/api/v2/runs/${{ env.RUN_ID }} \
-              | jq -r '.data.attributes.status')
+              https://app.terraform.io/api/v2/runs/${{ env.RUN_ID }})
+
+            status=$(echo $response | jq -r '.data.attributes.status')
 
             echo "Terraform run status: $status"
 
@@ -93,7 +104,7 @@ jobs:
             fi
 
             echo "Waiting for Terraform run to complete..."
-            sleep 30 # Wait for 30 seconds before checking again
+            sleep 30
           done
             
       # Build, package, and upload your Gatling project 
