Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -83,10 +83,7 @@ jobs:
             echo "Waiting for Terraform run to complete..."
             sleep 15
           done
-          
-      - name: Control Plane Bootup
-        run: sleep 60
-          
+
       - name: Checkout
         uses: actions/checkout@v3
         
@@ -97,7 +94,10 @@ jobs:
           java-version: '21'
           cache: 'maven'
           
-      - name: Build and upload Gatling package
+      - name: Bootup Control Plane 
+        run: sleep 60
+          
+      - name: Deploy Gatling Enterprise Package & Simulation
         run: |
           mvn gatling:enterpriseDeploy -Dgatling.enterprise.apiToken=${{ env.GATLING_ENTERPRISE_API_TOKEN }} > build.log 2>&1
           package_id=$(grep "Package uploaded" build.log | sed -n "s/.*id='\(.*\)'.*/\1/p")
@@ -143,3 +143,35 @@ jobs:
           echo "destroy_response=$destroy_response" >> $GITHUB_ENV
           destroy_run_id=$(echo $destroy_response | jq -r '.data.id')
           echo "DESTROY_RUN_ID=$destroy_run_id" >> $GITHUB_ENV
+          
+      - name: Wait for Terraform HCP Destroy Run Completion
+        run: |
+          start_time=$(date +%s)
+          timeout=240
+
+          while true; do
+            current_time=$(date +%s)
+            elapsed_time=$((current_time - start_time))
+
+            if [ $elapsed_time -gt $timeout ]; then
+              echo "Error: Terraform destroy run exceeded maximum polling duration of 4 minutes."
+              exit 1
+            fi
+
+            destroy_response=$(curl \
+              --header "Authorization: Bearer $TF_API_TOKEN" \
+              --header "Content-Type: application/vnd.api+json" \
+              --request GET \
+              https://app.terraform.io/api/v2/runs/$DESTROY_RUN_ID)
+
+            destroy_status=$(echo $destroy_response | jq -r '.data.attributes.status')
+
+            echo "Terraform destroy run status: $destroy_status"
+
+            if [[ "$destroy_status" == "applied" || "$destroy_status" == "errored" || "$destroy_status" == "canceled" ]]; then
+              break
+            fi
+
+            echo "Waiting for Terraform destroy run to complete..."
+            sleep 15
+          done
